export const COMMON_SITE_INFO_RECEIVED = "COMMON_SITE_INFO_RECEIVED";

export const HOME_AD_SLIDE_IMAGES_RECEIVED = "HOME_AD_SLIDE_IMAGES_RECEIVED";


export const PRODUCTS_RESET = "PRODUCTS_RESET";
export const PRODUCTS_SET = "PRODUCTS_SET";
export const PRODUCTS_IS_FETCHING = "PRODUCTS_IS_FETCHING";
export const PRODUCTS_ON_SERVER_QTY_SET = "PRODUCTS_ON_SERVER_QTY_SET";
export const PRODUCTS_PUSHED = "PRODUCTS_PUSHED";
export const PRODUCTS_BESTSELLERS_PUSHED = "PRODUCTS_BESTSELLERS_PUSHED";
export const PRODUCTS_NOVELTIES_PUSHED = "PRODUCTS_NOVELTIES_PUSHED";
export const PRODUCT_FAVORITE_TOGGLED = "PRODUCT_FAVORITE_TOGGLED";


export const COLLECTIONS_RESET = "COLLECTIONS_RESET";
export const COLLECTIONS_IS_FETCHING = "COLLECTIONS_IS_FETCHING";
export const COLLECTIONS_PUSHED = "COLLECTIONS_PUSHED";

export const NEWS_RESET = "NEWS_RESET";
export const NEWS_PUSHED = "NEWS_PUSHED";

export const BASKET_RESET = "BASKET_RESET";
export const BASKET_SET = "BASKET_SET";
export const BASKET_ITEM_SET = "BASKET_ITEM_SET";
export const BASKET_ITEM_REMOVED = "BASKET_ITEM_REMOVED";
export const BASKET_CALCULATED = "BASKET_CALCULATED";