export const COMMON_SITE_INFO_RECEIVED = "COMMON_SITE_INFO_RECEIVED";

export const SLIDER_IMAGES_RECEIVED = "SLIDER_IMAGES_RECEIVED";

export const PRODUCTS_BESTSELLERS_RESET = "PRODUCTS_BESTSELLERS_RESET";
export const PRODUCTS_BESTSELLERS_PUSHED = "PRODUCTS_BESTSELLERS_PUSHED";

export const PRODUCTS_NOVELTIES_RESET = "PRODUCTS_NOVELTIES_RESET";
export const PRODUCTS_NOVELTIES_PUSHED = "PRODUCTS_NOVELTIES_PUSHED";

export const COLLECTIONS_RESET = "COLLECTIONS_RESET";
export const COLLECTIONS_PUSHED = "COLLECTIONS_PUSHED";

export const NEWS_RESET = "NEWS_RESET";
export const NEWS_PUSHED = "NEWS_PUSHED";