export const COMMON_SITE_INFO_RECEIVED = "COMMON_SITE_INFO_RECEIVED";

export const SLIDER_IMAGES_RECEIVED = "SLIDER_IMAGES_RECEIVED";

export const CARDS_BESTSELLERS_RESET = "CARDS_BESTSELLERS_RESET";
export const CARDS_BESTSELLERS_PUSHED = "CARDS_BESTSELLERS_PUSHED";

export const CARDS_NOVELTIES_RESET = "CARDS_NOVELTIES_RESET";
export const CARDS_NOVELTIES_PUSHED = "CARDS_NOVELTIES_PUSHED";

export const COLLECTIONS_RESET = "COLLECTIONS_RESET";
export const COLLECTIONS_PUSHED = "COLLECTIONS_PUSHED";

export const NEWS_RESET = "NEWS_RESET";
export const NEWS_PUSHED = "NEWS_PUSHED";