

export const SLIDER_CARDS_RECEIVED = "SLIDER_CARDS_RECEIVED";




export const CARDS_BESTSELLERS_RESET = "CARDS_BESTSELLERS_RESET";
export const CARDS_BESTSELLERS_PUSHED = "CARDS_BESTSELLERS_PUSHED";

export const CARDS_NOVELTIES_RESET = "CARDS_NOVELTIES_RESET";
export const CARDS_NOVELTIES_PUSHED = "CARDS_NOVELTIES_PUSHED";